### ISSUE TITLE
Method Not Found Error Upon Startup SE v1.185

### ISSUE THREAD

**Issue by jornjohnson** [krypt-lynx/SE-SpeedLimitFix#1]
I am currently seeing the following error upon startup on the newest stable SE version post physics overhaul.

`2017-11-19 09:54:16.324 - Thread:  43 ->  Exception occured: System.MissingMethodException: Method not found: 'Void Sandbox.MySandboxGame.Invoke(System.Action)'.
   at SpeedLimitFix.Downloader.DoUpdateCheckDone(XmlDocument doc)
   at SpeedLimitFix.Downloader.StartUpdateCheck()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()`

**Comment by krypt-lynx** [comment]
Keen fixed this issue in vanilla, so, you don't need this plugin anymore. You can safely remove it now.

Unfortunately, exact same update broke notification feature of plugin I'm planed to use to notify users about plugin update of vanilla fix.
